version: "3.9"
services:
  mi_app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql_proyect
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_proyect:3306/productos_test
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true

  mysql_proyect:
    image: mysql
    container_name: mysql_proyect
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=productos_test
